<?php

// $Id: branch
/*
 * @file: File containing many helping functions for branche pages.
 */

/*
 * Implementation of hook_init().
 */
function trojan_contact_init() {
  module_load_include('inc', 'trojan_contact', 'forms/contact.home');
  module_load_include('inc', 'trojan_contact', 'forms/contact.employee.login');
  module_load_include('inc', 'trojan_contact', 'forms/contact.sales.services');
  module_load_include('inc', 'trojan_contact', 'forms/contact.training');
  module_load_include('inc', 'trojan_contact', 'forms/contact.branch');
 module_load_include('inc', 'trojan_contact', 'forms/contact.popup');
}

/*
 * Implementation of hook_menu().
 */
function trojan_contact_menu() {
  $items = array();

  $items['tc/test'] = array(
    'title' => 'Application Form', 
    'page callback' => 'trojan_contact_test', 
    'access arguments' => array('access content'), 
    'type' => MENU_CALLBACK,
  );
  
  $items['health_safety'] = array(
    'title' => 'Health & Safety Certificate', 
    'page callback' => 'health_safety', 
    'access arguments' => array('access content'), 
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/*
 * Implementation of hook_menu().
 */
function trojan_contact_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  global $base_url;
  switch ($op) {
    case 'view':
      if($node->type == 'page') {
	    $path = drupal_get_path('module', 'trojan_contact');
		$pathinfo = pathinfo($node->field_page_video2[0]['filepath']);

        if(isset($pathinfo['extension']) && $pathinfo['extension'] == 'mov') {
		  $file = $base_url .'/'. $node->field_page_video2[0]['filepath'];
		  $node->content['body']['#value'] = str_replace('[video]', _trojan_contact_embed_mov($file), $node->content['body']['#value']);

		}
        else if(isset($pathinfo['extension']) && $pathinfo['extension'] == 'mp4') {
		  $pathinfo = pathinfo($node->field_page_video2[0]['filepath']);
          drupal_add_js("{$path}/jwplayer/jwplayer.js");
		  drupal_add_js('
		    $(document).ready(function() {
		      jwplayer("mediaplayer").setup({
			    flashplayer: "'. $base_url .'/'. $path .'/jwplayer/player.swf",
			    file: "'. $base_url .'/'. $node->field_page_video2[0]['filepath'] .'",
			    width: 942,
			    height: 529
              });
		    });', 'inline');
		  $node->content['body']['#value'] = str_replace('[video]', '<div id="mediaplayer">JW Player goes here</div>', $node->content['body']['#value']);
	    }
        //_trojan_contact_video_field('field_page_video', &$node);
      }
      break;
  }
}

function _trojan_contact_embed_mov($file) {
return '
  <object classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B"
    codebase="http://www.apple.com/qtactivex/qtplugin.cab"
    width="942" height="529">
    <param name="src" value="'. $file .'" />
    <param name="controller" value="true" /> 
    <param name="autoplay" value="true" />
    <!--[if !IE]>--> 
  	  <object type="video/quicktime" 
		 data="sample-video.qtl" 
		 width="942" height="529"> 
		  <param name="autoplay" value="true" /> 
		  <param name="controller" value="true" />
	  </object> 
	<!--<![endif]--> 
  </object>';
}

function _trojan_contact_video_field($field_type, &$node) {
  $system_types = _content_type_info();
  $field = $system_types['fields'][$field_type];
  $field['widget'] = $system_types['content types'][$node->type]['fields'][$field_type]['widget'];
  $options = array('autoplay' => false);
  
  $video = theme('emvideo_video_video', $field, $node->{$field_type}[0], 'emvideo_embed', $node, $options);
  $node->content['body']['#value'] = str_replace('[video]', $video, $node->content['body']['#value']);
}

function health_safety(){
    global $base_url;
	return '<div style="width: 850px; height: 824px">
      <img src="'.$base_url.'/sites/default/files/trojan/healthcertificate2.jpg" />
    </div>';
}


/*
 * Callback page.
 */
function trojan_contact_test() {
  return drupal_get_form('trojan_contact_popup_form');
}

/*
 * Implementation of hook_theme().
 */
function trojan_contact_theme() {
  $path = drupal_get_path('module', 'trojan_contact');
  return array(
    'trojan_contact_home_form' => array(
      'template' => 'theme/home-contact-form',
      'arguments' => array('form' => null, 'vars' => NULL),
	  'path' => $path,
    ),
	'trojan_contact_employee_login_form' => array(
      'template' => 'theme/employee-login-contact-form',
      'arguments' => array('form' => null, 'vars' => NULL),
	  'path' => $path,
    ),
	'trojan_contact_sales_services_form' => array(
      'template' => 'theme/sales-services-contact-form',
      'arguments' => array('form' => null, 'vars' => NULL),
	  'path' => $path,
    ),
	'trojan_contact_training_form' => array(
      'template' => 'theme/training-contact-form',
      'arguments' => array('form' => null, 'vars' => NULL),
	  'path' => $path,
    ),
	'trojan_contact_popup_form' => array(
      'template' => 'theme/popup-contact-form',
      'arguments' => array('form' => null, 'vars' => NULL),
	  'path' => $path,
    ),
	'trojan_contact_branch_form' => array(
      'template' => 'theme/branch-contact-form',
      'arguments' => array('form' => null, 'vars' => NULL),
	  'path' => $path,
    ),
	'mail_contact_home' => array(
      'template' => 'theme/emails/mail-contact-home',
      'arguments' => array('vars' => NULL),
	  'path' => $path,
    ),
	'mail_contact_employee_login' => array(
      'template' => 'theme/emails/mail-contact-employee-login',
      'arguments' => array('vars' => NULL),
	  'path' => $path,
    ),
	'mail_contact_sales_services' => array(
      'template' => 'theme/emails/mail-contact-sales-services',
      'arguments' => array('vars' => NULL),
	  'path' => $path,
    ),
	'mail_contact_training' => array(
      'template' => 'theme/emails/mail-contact-training',
      'arguments' => array('vars' => NULL),
	  'path' => $path,
    ),
	'mail_contact_popup' => array(
      'template' => 'theme/emails/mail-contact-popup',
      'arguments' => array('vars' => NULL),
	  'path' => $path,
    ),
	'mail_contact_branch' => array(
      'template' => 'theme/emails/mail-contact-branch',
      'arguments' => array('vars' => NULL),
	  'path' => $path,
    ),
  );
}

function trojan_contact_mail($key, &$message, $params) {
  $language = $message['language'];
  $variables = user_mail_tokens($params['account'], $language);
  
  $headers = array(
    'MIME-Version' => '1.0',
    'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
    'Content-Transfer-Encoding' => '8Bit',
    'X-Mailer' => 'Drupal'
  );

  foreach ($headers as $key2 => $value) {
    $message['headers'][$key2] = $value;
  }

  switch($key) {
    case 'contact_home':
      $message['subject'] = t($params['subject'], $variables, $language->language);
      $message['body'][] = theme('mail_contact_home', $params);
      break;

	case 'contact_employee_login':
      $message['subject'] = t($params['subject'], $variables, $language->language);
      $message['body'][] = theme('mail_contact_employee_login', $params);
      break;

	case 'contact_sales_services':
      $message['subject'] = t($params['subject'], $variables, $language->language);
      $message['body'][] = theme('mail_contact_sales_services', $params);
      break;

	case 'contact_training':
      $message['subject'] = t($params['subject'], $variables, $language->language);
      $message['body'][] = theme('mail_contact_training', $params);
      break;

	case "contact_popup":
      //$message['subject'] = 'test'; //t($params['subject'], $variables, $language->language);
			$message['subject'] = t($params['subject'], $variables, $language->language);
      $message['body'][] = theme('mail_contact_popup', $params);
      break;

	case 'contact_branch':
      $message['subject'] = t($params['subject'], $variables, $language->language);
      $message['body'][] = theme('mail_contact_branch', $params);
      break;
  }
}

/*
 * Implementation of hook_form().
 */
function trojan_contact_popup_form($form_state = '') {

  $form = array();

  $form['date_of_application'] = array(
    '#type' => 'textfield', 
    '#title' => t('Date of Application'), 
    '#size' => 25, 
  );

  $form['postion_applying_for'] = array(
    '#type' => 'checkboxes', 
    '#title' => t('Postion applying for'), 
	'#options' => array(
	  'H2S Safety ',
	  'First Aid',
	  'FireFighter',
	  'Other',
	)
  );
  
  $form['postion_applying_for_other'] = array(
    '#type' => 'textfield', 
	'#size' => 15, 
  );

  $form['name'] = array(
    '#type' => 'textfield', 
    '#title' => t('Name'), 
  );

  $form['date_of_birth'] = array(
    '#type' => 'textfield', 
    '#title' => t('Date of Birth'), 
  );

  $form['Address1'] = array(
    '#type' => 'textfield', 
    '#title' => t('Address'), 
  );

  $form['Address2'] = array(
    '#type' => 'textfield', 
    '#title' => t(''), 
  );

  $form['Address3'] = array(
    '#type' => 'textfield', 
    '#title' => t(''), 
  );

  $form['Phone'] = array(
    '#type' => 'textfield', 
    '#title' => t('Phone'), 
  );

  $form['Mobile'] = array(
    '#type' => 'textfield', 
    '#title' => t('Mobile'), 
  );

  $form['Email'] = array(
    '#type' => 'textfield', 
    '#title' => t('Email'), 
  );

  $form['Previous_Employer1'] = array(
    '#type' => 'textfield', 
    '#title' => t('Previous Employer'), 
  );

  $form['Date_Started1'] = array(
    '#type' => 'textfield', 
    '#title' => t('Date Started'), 
  );

  $form['Position1'] = array(
    '#type' => 'textfield', 
    '#title' => t('Position'), 
  );

  $form['Date_Ended1'] = array(
    '#type' => 'textfield', 
    '#title' => t('Date Ended'), 
  );

  $form['Phone_number1'] = array(
    '#type' => 'textfield', 
    '#title' => t('Phone number'), 
  );

  $form['Reason_for_Leaving1'] = array(
    '#type' => 'textfield', 
    '#title' => t('Reason for Leaving'), 
  );

  $form['Previous_Employer2'] = array(
    '#type' => 'textfield', 
    '#title' => t('Previous Employer'), 
  );

  $form['Date_Started2'] = array(
    '#type' => 'textfield', 
    '#title' => t('Date Started'), 
  );

  $form['Position2'] = array(
    '#type' => 'textfield', 
    '#title' => t('Position'), 
  );

  $form['Date_Ended2'] = array(
    '#type' => 'textfield', 
    '#title' => t('Date Ended'), 
  );

  $form['Phone_number2'] = array(
    '#type' => 'textfield', 
    '#title' => t('Phone number'), 
  );

  $form['Reason_for_Leaving2'] = array(
    '#type' => 'textfield', 
    '#title' => t('Reason for Leaving'), 
  );

  $form['Previous_Employer3'] = array(
    '#type' => 'textfield', 
    '#title' => t('Previous Employer'), 
  );

  $form['Date_Started3'] = array(
    '#type' => 'textfield', 
    '#title' => t('Date Started'), 
  );

  $form['Position3'] = array(
    '#type' => 'textfield', 
    '#title' => t('Position'), 
  );

  $form['Date_Ended3'] = array(
    '#type' => 'textfield', 
    '#title' => t('Date Ended'), 
  );

  $form['Phone_number3'] = array(
    '#type' => 'textfield', 
    '#title' => t('Phone number'), 
  );

  $form['Reason_for_Leaving3'] = array(
    '#type' => 'textfield', 
    '#title' => t('Reason for Leaving'), 
  );

  $form['Secondary_Institution'] = array(
    '#type' => 'textfield', 
    '#title' => t('Secondary Institution'), 
  );

  $form['Graduated?'] = array(
    '#type' => 'textfield', 
    '#title' => t('Graduated?'), 
  );

  $form['Post-Secondary_Institution'] = array(
    '#type' => 'textfield', 
    '#title' => t('Post-Secondary Institution'), 
    '#size' => 90,
  );

  $form['Program'] = array(
    '#type' => 'textfield', 
    '#title' => t('Program'), 
  );

  $form['Years_Completed?'] = array(
    '#type' => 'textfield', 
    '#title' => t('Years Completed?'), 
  );

  $form['How_much_experience_do_you_have_in_the_oil_and_gas_industry?'] = array(
    '#type' => 'textfield', 
    '#title' => t('How much experience do you have in the oil and gas industry?'), 
  );

  $form['How_much_experience_do_you_have_in_this_position?'] = array(
    '#type' => 'textfield', 
    '#title' => t('How much experience do you have in this position?'), 
	'#size' => 70,
  );

  $form['What_are_you_looking_to_obtain_through_this_position?'] = array(
    '#type' => 'textfield', 
    '#title' => t('What are you looking to obtain through this position?'), 
	'#size' => 70,
  );

  $form['What_are_you_looking_to_obtain_through_this_position?1'] = array(
    '#type' => 'textfield', 
	'#size' => 121,
  );

  $form['Do_you_consider_this_position_a_stepping_stone?'] = array(
    '#type' => 'textfield', 
    '#title' => t('Do you consider this position a "stepping stone"? '), 
    '#size' => 75,
  );

  $form['If_yes_to_what?'] = array(
    '#type' => 'textfield', 
    '#title' => t('If yes, to what?'), 
    '#size' => 85,
  );

  $form['Would_you_consider_this_position_a_job_or_a_career?'] = array(
    '#type' => 'textfield', 
    '#title' => t('Would you consider this position a job or a career?'), 
    '#size' => 70,
  );

  $form['What_are_your_expected_starting_wages_for_this_position?'] = array(
    '#type' => 'textfield', 
    '#title' => t('What are your expected starting wages for this position?'), 
    '#size' => 65,
  );

  $form['What_are_your_short_term_goals_up_to_1_year_?'] = array(
    '#type' => 'textfield', 
    '#title' => t('What are your short term goals (up to 1 year)?'), 
    '#size' => 75,
  );

  $form['What_are_your_short_term_goals_up_to_1_year_?1'] = array(
    '#type' => 'textfield', 
    '#title' => t(''), 
    '#size' => 121,
  );

  $form['What_are_your_long_term_goals_1-5_years_?'] = array(
    '#type' => 'textfield', 
    '#title' => t('What are your long term goals (1-5 years)?'), 
    '#size' => 80,
  );

  $form['What_are_your_long_term_goals_1-5_years_?1'] = array(
    '#type' => 'textfield', 
    '#title' => t(''), 
    '#size' => 121,
  );

  $form['resume'] = array(
    '#type' => 'file', 
    '#title' => t('Upload your resume'), 
    '#size' => 40,
  );

  $form['drivers'] = array(
    '#type' => 'file', 
    '#title' => t('Upload your drivers abstract'), 
    '#size' => 40,
  );
  
  $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'));

  $form['#theme'] = 'trojan_contact_popup_form';

  return $form;

}



/*
 * Implementation of hook_form_submit().
 */
function trojan_contact_popup_form_submit($form, $form_state) {
  global $user;
  $values = $form_state['values'];
 // $site_mail = variable_get('site_mail', '');
//	$site_mail ="aleah@thecreativepatch.com,pamilahere@gmail.com";
	$site_mail ="pamilahere@gmail.com";
  $response = drupal_mail('trojan_contact', 'contact_popup', $site_mail, user_preferred_language($user), $values);
echo "test";
 drupal_set_message('Message has been sent ');
 
// exit;
	
	
}