<?php

// $Id: services.module $
/**
 * Implementation of hook_perm
 * @file services.module
 */
function services_perm() {
    return array('services intro text');
}

/**
 * Implementation of hook_menu()
 */
function services_menu() {

    $items['services_intro'] = array(
        'title' => 'Services Intro',
        'page callback' => 'services_intro_callback',
        'access arguments' => array('services intro text'),
        'type' => MENU_NORMAL_ITEM,
    );
    
    $items['services'] = array(
        'title' => 'Services',
        'page callback' => 'services_callback',
        'access arguments' => array('services intro text'),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}


function services_callback(){
    $intro = variable_get('services_intro', '');
    $sql = "SELECT nid FROM {node} WHERE type = 'service'";
    $result = db_query($sql);
    while($row = db_fetch_object($result)){
        $data[$row->nid] = node_load($row->nid);
    }
    
    return theme('services_callback', $intro, $data);
}




function services_intro_callback() {
    return drupal_get_form('services_intro_form');
}

function services_intro_form() {

    $services_intro = variable_get('services_intro', '');

    $form['intro_text'] = array(
        '#type' => 'textarea',
        '#title' => 'Please Enter Introduction',
        '#default_value' => $services_intro,
        '#required' => true,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Update'),
    );



    return $form;
}

function services_intro_form_submit($form, &$form_state) {
    $intro_text = $form_state['values']['intro_text'];
    variable_set('services_intro', $intro_text);
}

function services_theme() {
    return array(
        'services_callback' => array(
            'arguments' => array('intro' => NULL, 'data' => NULL),
            'template' => 'services',
        )
    );
}